instance_groups:
- name: elasticsearch_master
  vm_type: t3.large

- name: elasticsearch_data
  instances: 4
  vm_type: t3.large
  update:
    max_in_flight: 2
    canaries: 2

- name: ingestor
  vm_type: t3.large

- name: maintenance
  vm_type: t3.large

- name: kibana
  vm_type: t3.xlarge
  jobs:
  - name: oauth2-proxy
    properties:
      redirect_url: https://logs-platform.fr-stage.cloud.gov/oauth2/callback
      oidc_issuer_url: https://opslogin.fr.cloud.gov/oauth/token

- name: smoke-tests
  vm_type: t3.small
  jobs:
  - name: smoke_tests
    properties:
      smoke_tests:
        count_test:
          run: true
          minimum: 20000
          time_interval: "5m"
          time_field: "@timestamp"
          index_pattern: "logs-platform-*"

stemcells:
- alias: default
  name: bosh-aws-xen-hvm-ubuntu-bionic-go_agent
  version: latest
